version: "3"

services:
  api:
    build: .
    container_name: app-api-express
    env_file:
      - .env
    environment:
      MYSQL_HOST: db
      TZ: "America/Fortaleza"
    ports:
      - 8081:4000
    volumes:
      - ./:/usr/src/api
    networks:
      - app-tier 
    depends_on:
      - db
  db:
    image: mysql
    container_name: app-database-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    environment:
      TZ: "America/Fortaleza"
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - ./volume-database/:/var/lib/mysql
    networks:
      - app-tier 
networks:
  app-tier:
    driver: bridge
