version: "3"

services:
  api:
    build: .
    container_name: app-api-express
    ports:
      - 8081:4000
    volumes:
      - ./:/usr/src/api
  db:
    image: mysql
    container_name: app-database-mysql
      # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
      # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ./.env
    ports:
      - 3306:3306
    volumes:
      - ./volume-database/:/var/lib/mysql
